imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        handler_id: ~
        storage_id: session.storage.filesystem
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %kernel.cache_dir%/test.db

security:
    firewalls:
        main:
            http_basic: ~
