services:
    bug_track.form.type.user:
        class: BugTrackBundle\Form\Type\UserFormType
        calls:
            - ['setCanEditRoles', ['false']]
        tags:
            - { name: form.type }

    bug_track.listener.issue:
        class: BugTrackBundle\EventListener\IssueEventListener
        tags:
            - { name: kernel.event_subscriber }

    bug_track.security.voter.user:
        class:      BugTrackBundle\Security\Voter\UserVoter
        public:     false
        tags:
            - { name: security.voter }

    bug_track.security.voter.project:
        class:      BugTrackBundle\Security\Voter\ProjectVoter
        public:     false
        tags:
            - { name: security.voter }
